### PR TITLE
Fetchres dependency

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by laurieboyes** [comment]
Ha, uh, weird! How did you spot this?

**Comment by ironsidevsquincy** [comment]
Trying to use this in next-graphql-api

**Comment by laurieboyes** [comment]
Cool. I guess maybe it was relying on some other dependency in the app that uses it requiring it on its behalf :+1:

**Comment by ironsidevsquincy** [comment]
Yeah, exactly. Easily done

**Pull request merged**
